services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:4173"
    command: sh -c "npm run dev"