services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: custom-nginx
    ports:
      - "80:80"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node-vite-tailwind
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:4173"
    #before running this commands you should install vite manually into the container
    command: sh -c "cd /app && 
                    npm run dev"