services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  node:
    image: node:18.12
    container_name: node
    tty: true
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"