services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx

  node:
    image: node:18.12
    container_name: node
    tty: true
    volumes:
      - ./src:/var/www/html