services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mynginx
    ports:
      - "80:80"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: mynode
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:4173"
    command: sh -c "cd /app && 
                    npm run preview"