version: "3.9"
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:4173"
    working_dir: /app
    command: /bin/sh -c  "npm install && npm run dev"