services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: auth-ui-nginx
    ports:
      - "80:80"

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: auth-ui-node
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /app
    ports:
      - "3000:4173"
    working_dir: /app
    command: /bin/sh -c  "npm install && npm run dev"